export const ProductList = [
  {
    id: 1,
    name: "Product 1",
    price: 1,
    url: "https://images.pexels.com/photos/59945/strawberry-fruit-delicious-red-59945.jpeg",
    cart: false,
    quantity: 1,
    description: "This is a description",
  },
  {
    id: 2,
    name: "Product 2",
    price: 2,
    url: "https://images.pexels.com/photos/52533/orange-fruit-vitamins-healthy-eating-52533.jpeg",
    cart: false,
    quantity: 1,
    description: "This is a description",
  },
  {
    id: 3,
    name: "Product 3",
    price: 3,
    url: "https://images.pexels.com/photos/51312/kiwi-fruit-vitamins-healthy-eating-51312.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    cart: false,
    quantity: 1,
    description: "This is a description",
  },
  {
    id: 4,
    name: "Product",
    price: 3,
    url: "https://bizweb.dktcdn.net/100/344/954/files/neon-den-1.jpg?v=1632304030262",
    cart: false,
    quantity: 1,
    description: "This is a description",
  },
  {
    id: 5,
    name: "Product 5",
    price: 3,
    url: "https://bizweb.dktcdn.net/thumb/1024x1024/100/344/954/products/neon-den-2.jpg?v=1632387561037",
    cart: false,
    quantity: 1,
    description: "This is a description",
  },
  {
    id: 8,
    name: "Product 8",
    price: 3,
    url: "https://images.pexels.com/photos/51312/kiwi-fruit-vitamins-healthy-eating-51312.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    cart: false,
    quantity: 1,
    description: "This is a description",
  },
  {
    id: 7,
    name: "Product 7",
    price: 3,
    url: "https://cacanhkimgiang.com/wp-content/uploads/2020/08/ca_bay_mau_rung.jpg",
    cart: false,
    quantity: 1,
    description: "This is a description",
  },
  {
    id: 9,
    name: "Product 9",
    price: 3,
    url: "https://cabaymau.vn/wp-content/uploads/2019/12/ca-7-mau-tiger-king-1.jpg",
    cart: false,
    quantity: 1,
    description: "This is a description",
  },
  {
    id: 10,
    name: "Product 10",
    price: 3,
    url: "https://cabaymau.vn/wp-content/uploads/2019/12/ca-7-mau-tiger-king-1.jpg",
    cart: false,
    quantity: 1,
    description: "This is a description",
  },
  {
    id: 11,
    name: "Product 11",
    price: 3,
    url: "https://cabaymau.vn/wp-content/uploads/2019/12/ca-7-mau-tiger-king-1.jpg",
    cart: false,
    quantity: 1,
    description: "This is a description",
  },
  {
    id: 12,
    name: "Product 123",
    price: 3,
    url: "https://cabaymau.vn/wp-content/uploads/2019/12/ca-7-mau-tiger-king-1.jpg",
    cart: false,
    quantity: 1,
    description: "This is a description",
  },
  {
    id: 14,
    name: "Product 14",
    price: 3,
    url: "https://cabaymau.vn/wp-content/uploads/2019/12/ca-7-mau-tiger-king-1.jpg",
    cart: false,
    quantity: 1,
    description: "This is a description",
  },
];
